version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: django-db
      MYSQL_USER: django
      MYSQL_PASSWORD: django
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci

  web:
    build: .
    env_file:
      - .envrc
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000
    tty: true
    depends_on:
      - db
